In [1]:
import numpy as np # linear algebra
np.random.seed(10)

In [2]:
# datos de entrenamiento
data_x = np.array([[0,0], [0,1], [1,0], [1,1]])

data_y = np.array([[0], [1],[1],[0]])

print(data_x)

print(data_y)

# number of samples
N = 4

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [3]:
# inicialización de pesos de las dos capas {2 (entrada), 2 (primera), 1 (segunda)}, incluyen bias.
W_1 = np.random.randn(2, 2)
W_2 = np.random.randn(2, 1)
B_1 = np.random.randn(1, 2) # each column is a neuron, each row an input.
B_2 = np.random.randn(1, 1) # each column is a neuron, each row an input.

In [4]:
#sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [5]:
# forwardfeed
B_1_fixed = np.vstack([B_1] + [np.tile(B_1[0, :], (3, 1))])
L_1 = data_x.dot(W_1) + B_1_fixed
#print(L_1)
#print(L_1.shape)
L_1 = sigmoid(L_1)
#print(L_1)

L_1_bias = L_1#np.insert(L_1, 0, [1, 1, 1, 1], axis=1)
#print(L_1_bias)
#print(L_1_bias.shape)

B_2_fixed = np.vstack([B_2] + [np.tile(B_2[0, :], (3, 1))])
L_2 = L_1_bias.dot(W_2) + B_2_fixed
#print(L_2)
#print(L_2.shape)
L_2= sigmoid(L_2)
print(L_2)

output = L_2

[[0.49409956]
 [0.4406352 ]
 [0.50512681]
 [0.45605755]]


In [6]:
#backpropagation
print("output layer")
output_layer_error = output - data_y
print(output_layer_error)

output_layer_delta = output_layer_error * sigmoid_derivative(output)
print(output_layer_delta)

output_layer_weights_update = np.dot(L_1.T, output_layer_delta)/N
print(output_layer_weights_update)

output_layer_bias_gradient = np.sum(output_layer_delta, axis=0, keepdims=True) / N
print(output_layer_bias_gradient)

print("hidden layer")
hidden_layer_error = np.dot(output_layer_delta, W_2.T)
print(hidden_layer_error)
hidden_layer_delta = hidden_layer_error * sigmoid_derivative(L_1_bias) # podría ser L_1 ya que al no haber bias son lo mismo
print(hidden_layer_delta)
hidden_layer_weights_update = np.dot(data_x.T, hidden_layer_delta)/N
print(hidden_layer_weights_update)
hidden_layer_bias_gradient = np.sum(hidden_layer_delta, axis=0, keepdims=True) / N
print(hidden_layer_bias_gradient)


output layer
[[ 0.49409956]
 [-0.5593648 ]
 [-0.49487319]
 [ 0.45605755]]
[[ 0.1162822 ]
 [-0.13326709]
 [-0.11615038]
 [ 0.10828558]]
[[-0.00105756]
 [-0.00358338]]
[[-0.00621242]]
hidden layer
[[ 0.07225031 -0.08373313]
 [-0.08280364  0.09596371]
 [-0.07216841  0.08363821]
 [ 0.06728173 -0.07797488]]
[[ 0.01668988 -0.019544  ]
 [-0.02045785  0.02241076]
 [-0.01524996  0.01857448]
 [ 0.01576088 -0.01732705]]
[[ 0.00012773  0.00031186]
 [-0.00117424  0.00127093]]
[[-0.00081426  0.00102855]]


In [7]:
learning_rate = 0.1

print(W_2)
W_2 = W_2 - learning_rate*output_layer_weights_update
print(W_2)

print(B_2)
B_2 = B_2 - learning_rate*output_layer_bias_gradient
print(B_2)

print(W_1)
W_1 = W_1 - learning_rate*hidden_layer_weights_update
print(W_1)

print(B_1)
B_1 = B_1 - learning_rate*hidden_layer_bias_gradient
print(B_1)

[[ 0.62133597]
 [-0.72008556]]
[[ 0.62144173]
 [-0.71972722]]
[[0.00429143]]
[[0.00491267]]
[[ 1.3315865   0.71527897]
 [-1.54540029 -0.00838385]]
[[ 1.33157373  0.71524779]
 [-1.54528287 -0.00851094]]
[[0.26551159 0.10854853]]
[[0.26559301 0.10844567]]
